version: '3.8'
services:
  db:
    image: postgres:13.15
    environment:
      POSTGRES_DB: contas
      POSTGRES_USER: mauricio
      POSTGRES_PASSWORD: ejima
    ports:
      - "5433:5432"  # Alterada para evitar conflito
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contas
      SPRING_DATASOURCE_USERNAME: mauricio
      SPRING_DATASOURCE_PASSWORD: ejima
    network_mode: "host"

networks:
  app-network:

volumes:
  postgres_data:
